### ISSUE TITLE
Compilation fails!   Request your help and support!

### ISSUE THREAD

**Issue by 13613199288** [WJTung/GA-TSPCPP#2]
>
###Hello, I successfully compiled the optimal. cpp file and ga.cpp file.  I tried to compare these two algorithms in the environment 1-6 of your paper. 
Unfortunately, and found that optimal. Exe can get the result, but ga. exe can only get the result of environment 1, and nothing in environment 2-6.

**Comment by WJTung** [comment]
Hello @13613199288 , I just updated GA.cpp for solving the compilation errors you got yesterday.
Can you describe in more detail regarding "get nothing in environment 2-6"? GA.cpp works on my computer with `./GA test_case cell_num` (cell_num for test case 1-6 is 10, 14, 18, 20, 23, 26 respectively).

**Comment by 13613199288** [comment]
@WJTung  Thank you for your reply. I have sorted out the problems and sent them to your email (jie1202@gmail.com).

> 您好@ 13613199288，我刚刚更新了GA.cpp来解决您昨天遇到的编译错误。
> 您能否更详细地描述“在环境2-6中什么也得不到”？GA.cpp可在我的计算机上使用`./GA test_case cell_num`（测试用例1-6的cell_num分别为10、14、18、20、23、26）。

**Comment by 13613199288** [comment]
> Hello @13613199288 , I just updated GA.cpp for solving the compilation errors you got yesterday.
> Can you describe in more detail regarding "get nothing in environment 2-6"? GA.cpp works on my computer with `./GA test_case cell_num` (cell_num for test case 1-6 is 10, 14, 18, 20, 23, 26 respectively).

Thank you for your reply. I have sorted out the details of the mistakes and sent them to your email (jie1202@gmail.com).

**Comment by 13613199288** [comment]
> Hello @13613199288 , I just updated GA.cpp for solving the compilation errors you got yesterday.
> Can you describe in more detail regarding "get nothing in environment 2-6"? GA.cpp works on my computer with `./GA test_case cell_num` (cell_num for test case 1-6 is 10, 14, 18, 20, 23, 26 respectively).

Hello, I have good news!
I have just tried compiling your **updated GA.cpp file and found that it works in all environments**, although **I can't find the reason** why the old version of GACPP didn't get results.
**(In the old version of GA.cpp,** I found in my tests thatI can get the running result when ` cell_num<=10`; But then ` cell_num>10`,you get nothing.
